# Generated by Django 4.2.11 on 2024-03-16 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_upload', models.ImageField(blank=True, null=True, upload_to='college_images/')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('map_link', models.URLField(blank=True, null=True)),
                ('stream', models.CharField(blank=True, choices=[('Natural', 'Natural'), ('Social', 'Social')], max_length=10, null=True)),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('Telegram', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('Telegram', models.URLField(blank=True, null=True)),
                ('Years', models.IntegerField()),
                ('icon_upload', models.ImageField(blank=True, null=True, upload_to='department_images/')),
                ('icon_url', models.URLField(blank=True, null=True)),
                ('programs', models.CharField(blank=True, choices=[('extension', 'Extension'), ('regular', 'Regular'), ('both', 'Both')], max_length=10, null=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='MyApp.college')),
            ],
        ),
    ]
